sudo: false
language: php
php:
  - 5.3

before_install:
  - npm install

install:
  - travis_retry composer install --no-interaction --prefer-source;
  - travis_retry composer update --prefer-source --no-interaction --prefer-stable;

script:
  - gulp ci
